### ISSUE TITLE
Req: enhance readme

### ISSUE THREAD

**Issue by drew-512** [jsmouret/grpc-unity-package#1]
Thanks for your work on this.

Can you kindly add to the readme steps to go from a vanilla Unity install (macOS), to which fiels should go where, to getting the example project up and running?  Thanks!

**Comment by jsmouret** [comment]
I added steps to run the example. Let me know if it is clear enough.
Thanks :)

**Comment by drew-512** [comment]
Lovely, thanks!!  

After a solid couple days of research and feeding my head on GPRC, I think there'll be an increasing demand for having a meaty GRPC example that does stuff with a non-Unity server (Go in particular).  You could potentially benefit from that by host a said meaty demo project, especially as there is so much confusion getting GRPC+protobufs running reliably, portably, and demonstrates that Unity's GC isn't getting thrashed.

I'm biased since that is what we're gong for, but I was just surprised at the vacuum on the Unity side (and I think it's only b/c there's a lack of a comprehensive end-to-end template for newcomers).   If you're curious about what we're up to, check out http://plan.tools -- I'm down to connect further!
