### ISSUE TITLE
How to run server

### ISSUE THREAD

**Issue by Smiling-Robotics** [jsmouret/grpc-unity-package#11]
Hello, First thank you for putting in so much time to developing this repo it will be of huge assistance for me. I have a problem with what I think is my understanding of how to run the example client and server. I build and run the example after fallowing the instructions on the readme however when I hit the say hello button I get connection failed exception. It seems to me that a grpc client is not running and I am hoping you know what I am doing wrong, thank you in advance.

**Comment by jsmouret** [comment]
It looks like you don't have a gRPC server running.

You can start the basic helloworld server for C# https://github.com/grpc/grpc/tree/v1.24.0/examples/csharp/Helloworld/GreeterServer
or in any other language as described in https://grpc.io/docs/quickstart/csharp/
