### ISSUE TITLE
New project mystery

### ISSUE THREAD

**Issue by drew-512** [jsmouret/grpc-unity-package#2]
Hi!   Yes, so your existing example project tests ok. 

However, when I create a new Unity 2018.2 project (OS X), adding your .cs files, and adding the three asset dirs results in Visual Studio error on:

using Grpc.Core;

I can't figure out why you example project works while a newly-created one doesn't.  I tried adding three dirs to the .csproj xml but they just get removed and nothing changes.

**Comment by jsmouret** [comment]
Have you extracted the zip file from [releases](https://github.com/jsmouret/grpc-unity-package/releases) in Assets/Plugins folder ?

Maybe check that the Scripting Runtime Version is set to .NET 4.x equivalent.

What is the exact error from Visual Studio ?

**Comment by drew-512** [comment]
Nailed it!  Sorry -- pretty green in this IDE.  :\
