### ISSUE TITLE
Error when compiling on IOS

### ISSUE THREAD

**Issue by diegoseso** [jsmouret/grpc-unity-package#4]
Hello, I am facing the following Issue when compiling to IOS:

![image](https://user-images.githubusercontent.com/7034138/46337407-b65a4f80-c62d-11e8-9a73-c5f7e85c6151.png)

Using the very same library works ok on Android, have you faced that problem ? It seems it has something to do with reflection no valid in Objective-C, could it be ? Sorry but I am no expert on the subject.

**Comment by jsmouret** [comment]
gRPC team now has an official/experimental package for Unity.
You can find it on the daily build page https://packages.grpc.io
Click on the link on the build ID column and it will take you to a page where you can find a zip file for Unity. That version doesn't have this bug.

I should probably update the readme :)
