### ISSUE TITLE
It cannot be compiled on UWP, IL2CPP Backend

### ISSUE THREAD

**Issue by MohsenneChaverdie** [jsmouret/grpc-unity-package#6]
I described [here](https://stackoverflow.com/questions/53488605/unity-cannot-build-grpc-project-for-uwp-with-il2cpp-backend), what I have done. So far I failed to compile it. 

I was wondering, if you have any idea or hint or something that I can try. Thanks in advance.

**Comment by jsmouret** [comment]
You can try adding something like this file in your Unity Plugins folder:
https://github.com/jsmouret/grpc-unity-package/blob/master/Plugins/Grpc.Core/runtimes/grpc_csharp_ext_stub.c

**Comment by MohsenneChaverdie** [comment]
First of thanks for your response. I just included it in the build by adding it to the project and set its platform to "any". I built it, it did not work. 

![image](https://user-images.githubusercontent.com/16707824/49255365-1736b600-f42c-11e8-801d-76346da33e08.png)

I tried to change the __Internal to the name of the script. It did not work out.
![image](https://user-images.githubusercontent.com/16707824/49255427-43523700-f42c-11e8-8c91-ee8052547984.png)

I tried to manually reference it. I did not work out.
![image](https://user-images.githubusercontent.com/16707824/49255474-667ce680-f42c-11e8-845f-3f4e3604aa61.png)

How do you suggest me include it? 

There is a Script, called BuildHelper in your repository. It is written for iOS, do you think I need something like that for UWP?

Thanks in advance for your help.

**Comment by MohsenneChaverdie** [comment]
I just looked at provided .dlls for Win in the plugin folder. In Unity they are not included for WSA player by default, I included them, but I got @dlopen error.

![image](https://user-images.githubusercontent.com/16707824/49259185-98944580-f438-11e8-8b26-fac60c3c9fe5.png)

**Comment by MohsenneChaverdie** [comment]
I also tried to reference .c script in Linker, Project Properties in VS. But again, it did not make any change.

![image](https://user-images.githubusercontent.com/16707824/49259243-df823b00-f438-11e8-8373-3a3d29c7edf4.png)

**Comment by MohsenneChaverdie** [comment]
Ok, it works. But if I tell you how, you are not going to believe it. ;)

Remember I mentioned above that I am getting "dlopen" errors. I searched it in repository and I changed some methods. 

A class called: Bulk_Grpc.Core_2.cpp
![image](https://user-images.githubusercontent.com/16707824/49295938-47776680-f4b7-11e8-96db-c98aa460fa45.png)

Commenting out: extern "C" intptr_t DEFAULT_CALL dlopen(char*, int32_t);
and defining it like: void dlopen(char*, int32_t) {}

![image](https://user-images.githubusercontent.com/16707824/49296060-8c030200-f4b7-11e8-9642-c853b5ce9625.png)

Then I got, dlsym:
Commenting out: extern "C" intptr_t DEFAULT_CALL dlsym(intptr_t, char*);
and defining it like: void dlsym(intptr_t, char*) {}

![image](https://user-images.githubusercontent.com/16707824/49296228-f451e380-f4b7-11e8-982b-a0ebb1bd8673.png)

Then I got, dlerror:
comment out: extern "C" intptr_t DEFAULT_CALL dlerror(); 
close to it write: void dlerror() {}
![image](https://user-images.githubusercontent.com/16707824/49370667-3025bc80-f6f5-11e8-9b0e-a7431b8bf9b6.png)

one method below it, named: Mono_dlerror_mXXXXXXX,
change return type to "NULL";

![image](https://user-images.githubusercontent.com/16707824/49370651-2308cd80-f6f5-11e8-980d-17b70cb73143.png)

**Comment by MohsenneChaverdie** [comment]
Now, problem is that, I need to do it every time I am making a build. Do you know how it is possible to provide dlopen, dlsym and dlerror in your Stub file? I tried it, but unfortunately, it did not work for me.

**Comment by MohsenneChaverdie** [comment]
Ok, Problem solved. I just documented it under my question in [StackOverflow](https://stackoverflow.com/questions/53488605/unity-cannot-build-grpc-project-for-uwp-with-il2cpp-backend/53600402#53600402). Thanks again.
