### ISSUE TITLE
Where is located the .proto file ? 

### ISSUE THREAD

**Issue by lcpages** [jsmouret/grpc-unity-package#8]
Hey ! I like your repository. We are trying to build a grpc client side from a Unity project and we are wondering how are generated the HelloWorld.cs and the HelloWorldGrpc.cs in your project ? 

After placing the plugins package in the Assets directory, where is located the .proto file that allows us to generate the .cs files ? 

Thank you !

**Comment by jsmouret** [comment]
It is using the .proto and example server from https://grpc.io/docs/quickstart/csharp.html

You're welcome :)
