### ISSUE TITLE
How to create the classes generated from the proto file?

### ISSUE THREAD

**Issue by GowthamanG** [jsmouret/grpc-unity-package#9]
I am working on a project with Unity. I've downloaded your grpc-unity-package. How do I compile the proto file? I tried to by using this command "dotnet build", but I don't get any generated classes. Where and how should I specify the direction for the generated files?

**Comment by jsmouret** [comment]
Hello,
I was about to point you to https://grpc.io/docs/tutorials/basic/csharp.html but it seems that they removed the command lines in favor of the MSBuild integration.
Roughly, you will need to get the Grpc.Tools package, and run something like:
```
Grpc.Tools/tools/windows_x64/protoc.exe
    --plugin=protoc-gen-grpc=Grpc.Tools/tools/windows_x64/grpc_csharp_plugin.exe
    --csharp_out=UnityProject/Assets/Scripts
    --grpc_out=UnityProject/Assets/Scripts
    helloworld.proto
```
Hope that helps :)

**Comment by GowthamanG** [comment]
Hi,

thanks, it works now. 

But the generated files don't recognize the Grpc.Core plugin, which I think comes with Grpc.Tool or with grpc-unity-plugin. One error for example is "using grpc = global::Grpc.Core" --> Cannot resolve symbol 'Grpc'. Do you know why? I'm working with the JetBrains Rider Editor.
